defaults:
  - _self_
  - override hydra/hydra_logging: none
  - override hydra/job_logging: none

seed: 0
debug: true
device: cpu
procedure: ???
run_name: ${get_run_name:${hydra:job.config_name}}
log_dir: ./logs/${now:%Y_%m_%d}_${now:%H_%M_%S}.${run_name}.${seed}
hydra:
  run:
    dir: ${log_dir}