# @package _global_
defaults:
  - /default 
  - _self_

procedure: em
detections_file: ./data/detections.pt
homographies_file: ./data/homographies.pt

epochs: 2

initial_state:
  variance: 100000

transition_model:
  num_layers: 3
  hidden_dim: 64
  scale: 1000
  initial_variance: 1
    
observation_model: 
  variance: 0.1

filter:
  num_particles: 100
  prediction_noise: 0
  nu: 5
  ess_scale: 0.5

smoother:
  num_trajectories: 32

em:
  lr: 0.001
  e_steps_per_epoch: 1
  m_steps_per_e_step: 4